### ISSUE TITLE
Java implementation of a StreamusServer

### ISSUE THREAD

**Issue by robtec** [MeoMix/StreamusServer#6]
The chromeextension is pretty sweet :), would the extension support a different server? as long as it had all the required API endpoints? such as one implemented in Java.

**Comment by cmacdonnacha** [comment]
I second this. It would be extremely useful if we could point to our own server.

**Comment by MeoMix** [comment]
There's no reason it wouldn't. 98% of the calls are RESTful (excluding some ShareCode stuff I've been meaning to try and tackle and bulk RESTful requests when saving lots of playlist items).

Feel free. Would love to see any changes you make. You might find it slightly challenging as the Streamus server is heavily dependent on NHibernate ORM which makes a lot of the stuff "just work." There's no SQL written anywhere.

**Comment by robtec** [comment]
Great, thats cool, SQL is messy in my opinion, would use Hibernate in Java too, and JPA.
Would you have any suggestion on which part of the API to start working on first?

**Comment by MeoMix** [comment]
I would take a look at the User model and note how it creates a Playlist
upon creation.

The hierarchy looks like:

User->Playlist->PlaylistItem->Song

So, you'll need those tables up and running and a User creating itself with
a GUID for its ID and an empty Playlist to work properly.

The first request Streamus makes to the server is either Create or
HasLinkedGoogleAccount method in UserController and then either
GetByGooglePlusId or Get if Create wasn't called.

Cheers

**Comment by robtec** [comment]
Cool, thanks @MeoMix for the help. I'll take a look at the controllers on the server :)
